[project]
name = "todo-rest"
version = "0.1.0"
description = "A simple todo list REST API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
]
